---
title: "The Canadian Podcast Listener 2019 Analysis"
author: "Aimin Amy Hu"
date: '2019-07-14'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

The term of podcasting comes from a combination of the words iPod(a personal digital audio player made by Apple) and broadcasting. Podcasting is a free service that allows internet users to listen to audio files on their computers or personal digital audio players. The podcasting platforms make many people's dreams come true-have their own radio show or writing songs heard by many people. Podcasting is not only used for entainment but also used for informational and educational purposes such as self-guided walking tours, training etc.

We understood that podcasting doesn't have long history. It was developed in 2004. As the personal digital devices are become more popular and enter into almost everyone's life including babies. within 100 million+ podcast listeners in the U.S (according to https://www.adamenfroy.com/podcast-hosting)and between 7 and 10 million Canadians are listening to podcasts(according to a study from late 2017 conducted by Ulster Media and the Globe and Mail). 

# Problem Statment
A rapdily increasing of updating personal digital devices and internet speed, they are many new things happen every day and also people share their personal experiences on social media. Podcast as a product which belongs to information technology era doesn't have long history, but it definitely affect our life. Podcasting has experienced a huge surge of interest in past several year (especially in the past three to four years). With Google reporting up to 10 million monthly searches for "podcast" via the search engine giant in 2019 based on information from Listennotes website. There are so much potentials in this field but also competition heats up for different podcast platforms. 

Per Mr.Jeff Vidler from Audience Insights Inc mentioned in the project meeting, Podcasts reply on ads for their finance support but they have challenge to target the podcast listeners. The one major reason is podcast platforms can see listeners download the podcast episodes but unable to get much information about the listeners as almost all podcasts are completely free and listeners don't need to put their information such as credit card or names.

This project will analyze the podcasing listeners in Canada. In Canada, this is just 3rd year to analysis the podcasting data. We will focuse on some research questions below but will not limite to these.
* Does podcasting will continue growth every year in Canada? 
* Do devices affect listeners to listen podcast? Are age and gender big factors to podcast?
* Does location affect people to listen to podcast?


# About

Audience Insights Inc. is a media research consultancy pulling together teams of media, research and data professionals to meet just about any assignment facing our clients. Whether it’s building audience, driving ad revenue, understanding impact of marketing or activating digital opportunities, we're flexible and fluid to fill gaps left in large, consolidated firms.

# Objectives

* To help Canadian podcast publishers and advertisers understand more about how to target different segments of podcast listeners.

* To inform business opportunites in this growing media sector.

* To identify growth areas compare with previous research.

# Project Scope
* Analyizing based on the dataset and survey provided by Audience Insights Inc.
* Trending Month to Month in Past 12 Months.
* Focus on podcast listeners segmentations: geographic, demographic, behavioral depending on available data.

# Project Milestones
* Sprint 1: Get dataset and clean up
* Sprint 2: Analyizing the dataset and get graphs and tables
* Sprint 3: Finaliz report

Timeline for each sprint is to be decided based on avaliablity of data.

# Dataset

By the end of June, we will have fresh data on podcasts listened to by more than 1,500 podcast listeners as we complete fieldwork on our 3rd Annual Canadian Podcast Listener study. We will have a comprehensive range of other data on both the individual podcasts (e.g., publisher, genre) and the listeners themselves (e.g., demographics, length of time listening to podcasts, preferred podcast platforms, attitudes towards advertising on podcasts). 

# Method and Language

This project will meet the objectives specified above through rigorous analysis of multiple data sources and synthesis into recommendations/suggestions for future business opportunites.
* Obtain and analyze the data on podcasts.
* Obtain and analyze the data on individual podcasts and the listeners.
* Method: Market Segmentation.
* R will be the language for this project.

# Expected Results

Deliver a capstone poject report to York University instructor Mr. Matthew Tenney and also to Audience Insights Inc. The report will include:
* Abstract
* List of Figures: figures will include graphs on use statistics of podcasts 
* List of Tables: tables will include listener's group
* List of Appendices: 
* Introduction: This section will include background information, about Audience Insights Inc. and objectives. These sections will be similar in topic but more in depth when compared to the same sections in this proposal.
* Methods of Analysis and Description of the Study Site:  The methods of analysis will be similar to the same section in this proposal, but more in depth.
